List dokonKerakliSozlar = [
  {"uz": "o‘rik", "esp": "albaricoque"},
  {"uz": "avokado", "esp": "aguacate"},
  {"uz": "ananas", "esp": "piña"},
  {"uz": "apelsin", "esp": "naranja"},
  {"uz": "tarvuz", "esp": "sandía"},
  {"uz": "banan", "esp": "plátanos, bananas"},
  {"uz": "qo‘y go‘shti", "esp": "carne de cordero"},
  {"uz": "bulochka", "esp": "bollo, panecillo"},
  {"uz": "cho‘chqa go‘shti", "esp": "jamón"},
  {"uz": "uzum", "esp": "uvas"},
  {"uz": "olcha", "esp": "guinda"},
  {"uz": "mol go‘shti", "esp": "carne de vaca"},
  {"uz": "greypfrut", "esp": "pomelo"},
  {"uz": "nok", "esp": "pera"},
  {"uz": "qovun", "esp": "melón"},
  {"uz": "saqich", "esp": "goma de mascar"},
  {"uz": "indeyka", "esp": "pavo"},
  {"uz": "yogurt", "esp": "yogur"},
  {"uz": "kolbasa", "esp": "-salchichon"},
  {"uz": "-qaynatilgan", "esp": "-mortadela"},
  {"uz": "-dudlangan", "esp": "-ahumado"},
  {"uz": "...konservalar", "esp": "conservas..."},
  {"uz": "-baliqli", "esp": "-de pescado"},
  {"uz": "-go‘shtli", "esp": "-de carne"},
  {"uz": "-sabzavotli", "esp": "-de legumbres"},
  {"uz": "konfetlar", "esp": "bombones"},
  {"uz": "kofe", "esp": "café"},
  {"uz": "-kapuchino", "esp": "-capuchino"},
  {"uz": "-tabiiy", "esp": "-natural"},
  {"uz": "-tez eruvchan", "esp": "-instantáneo"},
  {"uz": "-espresso", "esp": "-exprés"},
  {"uz": "1.krevetka 2.mayda baliq", "esp": "camarones"},
  {"uz": "jo‘ja", "esp": "pollo"},
  {"uz": "limon", "esp": "limón"},
  {"uz": "1.losos 2.go‘shti qizil baliq", "esp": "salmón"},
  {"uz": "marmelad", "esp": "mermelada"},
  {"uz": "zaytun", "esp": "aceitunas"},
  {"uz": "...yog‘i", "esp": "aceite..."},
  {"uz": "-jo‘xori", "esp": "-de maiz"},
  {"uz": "-zaytun", "esp": "-de oliva"},
  {"uz": "-kungaboqar", "esp": "-de girasol"},
  {"uz": "-soya", "esp": "-de soya"},
  {"uz": "saryog‘", "esp": "mantequilla"},
  {"uz": "mineral suv", "esp": "agua mineral"},
  {"uz": "sut", "esp": "leche"},
  {"uz": "muzqaymoq", "esp": "helado"},
  {"uz": "sabzavotlar", "esp": "legumbres"},
  {"uz": "bodring", "esp": "pepino"},
  {"uz": "yong‘oqlar", "esp": "nueces"},
  {"uz": "pashtet, qiyma go‘sht", "esp": "paté"},
  {"uz": "qalampir", "esp": "pimiento"},
  {"uz": "shaftoli", "esp": "melocotón"},
  {"uz": "1.kashnichsimon ko‘kat, 2.petrushka", "esp": "perejil"},
  {"uz": "kulcha", "esp": "galletas, pastas"},
  {"uz": "1.shirinlik 2. pirojnoe", "esp": "pastel"},
  {"uz": "pitssa", "esp": "pizza"},
  {"uz": "pomidor", "esp": "tomate"},
  {"uz": "salat", "esp": "lechuga"},
  {"uz": "sardelka", "esp": "salchichas de frankfort"},
  {"uz": "sardina", "esp": "sardinas"},
  {"uz": "shirinliklar", "esp": "azúcar"},
  {"uz": "mayda shakar", "esp": "azúcar molida"},
  {"uz": "cho‘chqa go‘shti", "esp": "carne de cerdo"},
  {"uz": "seld", "esp": "arebque"},
  {"uz": "shirinliklar", "esp": "dulces"},
  {"uz": "olxo‘ri", "esp": "ciruela"},
  {"uz": "sodali suv", "esp": "soda"},
  {"uz": "....sharbati", "esp": "zumo de..."},
  {"uz": "-apelsin", "esp": "-naranja"},
  {"uz": "-pomidor", "esp": "-tomate"},
  {"uz": "-olma", "esp": "-manzana"},
  {"uz": "tuz", "esp": "sal"},
  {"uz": "sosiskalar", "esp": "salchichas"},
  {"uz": "pishloq", "esp": "queso"},
  {"uz": "tonik", "esp": "tónica"},
  {"uz": "tort", "esp": "tarta"},
  {"uz": "1.shimoliy dengiz balig‘i. 2.treska", "esp": "bacalao"},
  {"uz": "maydalangan go‘sht", "esp": "carne picada"},
  {"uz": "mevalar", "esp": "frutas"},
  {"uz": "non", "esp": "pan"},
  {"uz": "...choy", "esp": "te..."},
  {"uz": "-ko‘k", "esp": "-verde"},
  {"uz": "-qora", "esp": "-negro"},
  {"uz": "shokolad", "esp": "chocolate"},
  {"uz": "olma", "esp": "manzana"},
  {"uz": "rezavor mevalar", "esp": "bayas"},
  {"uz": "tuxum", "esp": "huevo"},
];
