List dorixona = [
  {
    "uz": "Retseptlar orqali dorilarni berish bo'limi",
    "esp": "Despacho por recetas "
  },
  {"uz": "Navbatchi dorixona", "esp": "Farmacia de guardia"},
  {"uz": "Tashqi ishlatish", "esp": " uso tópico"},
  {"uz": "Retseptsiz", "esp": "Venta sin receta"},
  {"uz": "Iltimos, bu yerda...bormi?", "esp": "Por favor, ¿hay por aquí...."},
  {"uz": "-dorixona", "esp": "-una farmacia"},
  {"uz": "-navbatchi dorixona", "esp": "-una farmacia de guardia"},
  {
    "uz": "Mana bu retseptdagi dorini sotib olsam bo'ladimi?",
    "esp": "¿Puedo comprar un mediacemento según esta receta?"
  },
  {"uz": "Sizda...bormi?", "esp": "¿Usted tiene...?"},
  {
    "uz": "Menga.... qarshi biror narsa bering",
    "esp": "Deme, por favor, algo para..."
  },
  {"uz": "-yo'talga", "esp": "-tos"},
  {"uz": "-shamollashga", "esp": "-catarrro"},
  {"uz": "-bosh og'rig'iga", "esp": "-dolor de cabeza"},
  {"uz": "-oshqazon og'rig'iga", "esp": "-dolores de estómago"},
  {"uz": "-quyosh urishiga", "esp": "-quemaduras del sol"},
  {
    "uz": "Bu dori qanday ichiladi?",
    "esp": "¿Cómo se debe tomar esta medicina?"
  },
  {"uz": "Ovqatdan oldinmi?", "esp": "¿Es ayunas?"},
  {"uz": "Ovqatdan keyinmi?", "esp": "¿Después de las comidas?"},
  {"uz": "Kuniga necha mahal?", "esp": "¿Cuántas veces al día?"},
  {"uz": "...nechta?", "esp": "¿Cuántas...?"},
  {"uz": "-tabletkalar", "esp": "-tabletas"},
  {"uz": "-tomchilar", "esp": "-gotas"},
  {"uz": "Kerakli so'zlar", "esp": "Palabras utiles"},
  {"uz": "antibiotik", "esp": "antibiótico"},
  {"uz": "bint", "esp": "venda"},
  {"uz": "og'riq qoldiruvchi", "esp": "analgésico"},
  {"uz": "valeriana", "esp": "valeriana"},
  {"uz": "paxta", "esp": "algodón"},
  {"uz": "vitaminlar", "esp": "vitaminas"},
  {"uz": "harorat", "esp": "termómetro"},
  {"uz": "navbatchi dorixona", "esp": "farmacia de guardia"},
  {"uz": "harorat tushuruvchi", "esp": "febrifugo"},
  {"uz": "nina", "esp": "aguja"},
  {"uz": "yod", "esp": "yodo"},
  {"uz": "tomchilar", "esp": "gotas"},
  {"uz": "dori", "esp": "medicamento"},
  {"uz": "maz", "esp": "unguento"},
  {"uz": "doka", "esp": "gasa"},
  {"uz": "mikstura (aralashma)", "esp": "jarabe"},
  {"uz": "nastoyka (dimlama)", "esp": "tintura"},
  {"uz": "vodorod oksidi", "esp": "agua oxigenada"},
  {"uz": "pilyulalar", "esp": "pildoras"},
  {"uz": "pipetka (tomizgich)", "esp": "pípeta"},
  {"uz": "prezervativ", "esp": "preservativo"},
  {"uz": "retsept", "esp": "receta"},
  {"uz": "holsizlantiruvchi", "esp": "laxante"},
  {"uz": "uyqu dori", "esp": "somnífero"},
  {"uz": "soda", "esp": "soda"},
  {"uz": "qon bosimini pasaytiruvchi ", "esp": "bajar la tensión arterial"},
  {"uz": "Allergiyaga qarshi vosita", "esp": "alergia"},
  {"uz": "tabletkalar", "esp": "tabletas"},
  {"uz": "shprits", "esp": "jeringa"},
];
