List kasallik = [
  {"uz": "uyqusizlik", "esp": "insomnio"},
  {"uz": "...og'riq", "esp": "dolor..."},
  {"uz": "-yonboshdagi", "esp": "-en el costado"},
  {"uz": "-ko'krakdagi", "esp": "-en el pecho"},
  {"uz": "-qorindagi", "esp": "-en el estómago"},
  {"uz": "-orqadagi", "esp": "-en la espalda"},
  {"uz": "-yurakdagi", "esp": "-en el corazón"},
  {"uz": "-boshdagi", "esp": "-de cabeza"},
  {"uz": "-zirqiratadigan", "esp": "-molesto"},
  {"uz": "-o'tkir", "esp": "-agudo"},
  {"uz": "-bo'g'iq ", "esp": "-sordo"},
  {"uz": "bosh aylanishi ", "esp": "vértigo"},
  {"uz": "og'izni bemazaligi", "esp": "amargura en la boca"},
  {"uz": "isitma", "esp": "fiebre"},
  {"uz": "oshqazon qaynashi", "esp": "quemazón"},
  {"uz": "qorin dam bo'lishi ", "esp": "estreñimiento"},
  {"uz": "oshqazonda achishish", "esp": "ardor, pirosis"},
  {"uz": "yo'tal", "esp": "tos"},
  {"uz": "qon ketishi ", "esp": "hemorragia"},
  {"uz": "qon tuflash ", "esp": "esputo hemorrágico"},
  {"uz": "...qon bosimi", "esp": "presión arterial..."},
  {"uz": "-yuqori", "esp": "-alta"},
  {"uz": "-past", "esp": "-baja"},
  {"uz": "shamollash", "esp": "catarro"},
  {"uz": "hushdan ketish", "esp": "desmayo"},
  {"uz": "umumiy holsizlik ", "esp": "malestar general"},
  {"uz": "nafas qisishi", "esp": "ahogo"},
  {"uz": "ishtahani yo'qolishi", "esp": "falta de apetito"},
  {"uz": "yomon ishtaha", "esp": "mal apetito"},
  {"uz": "yuqori harorat", "esp": "temperatura elevada"},
  {"uz": "ich ketishi", "esp": "diarrea"},
  {"uz": "holsizlik", "esp": "debelidad"},
  {"uz": "uyqusirash", "esp": "somnolencia"},
  {"uz": "ko'ngil aynishi", "esp": "náuseas"},
];

