List kasblar = [
  {"uz": "Advokat", "esp": "Abogado"},
  {"uz": "Aktyor", "esp": "Actor"},
  {"uz": "Aktrisa", "esp": "Actriz"},
  {"uz": "Artist", "esp": "Artista"},
  {"uz": "Arxeolog", "esp": "Arqueólogo"},
  {"uz": "Bank xizmatchisi", "esp": "empleado de banco"},
  {"uz": "Biznesmen, tadbirkor", "esp": "hombre de negocios"},
  {"uz": "Biolog", "esp": "Biólogo"},
  {"uz": "Xisobchi", "esp": "Contable"},
  {"uz": "Veterinar", "esp": "Veterinario"},
  {"uz": "Xaydovchi", "esp": "Conductor"},
  {"uz": "Harbiy xizmatchi", "esp": "Militar"},
  {"uz": "Shiforkor (Umumiy amaliyot shifokori)", "esp": "Medico"},
  {"uz": "Genetik", "esp": "Genético"},
  {"uz": "Geofizik", "esp": "Geofísico"},
  {"uz": "Boshliq", "esp": "Jefe"},
  {"uz": "Dizayner", "esp": "Diseñador"},
  {"uz": "Diktor, suhandon", "esp": "Locutor"},
  {"uz": "Diplomat", "esp": "Diplomático"},
  {"uz": "Doktor, shifokor", "esp": "Doctor"},
  {"uz": "Jurnalist", "esp": "Periodista"},
  {"uz": "Muhandis", "esp": "Ingeniero"},
  {"uz": "Tarixchi", "esp": "Historiador"},
  {"uz": "Kommersant", "esp": "hombre de negocios"},
  {"uz": "Quruvchi", "esp": "Constructor"},
  {"uz": "Uchuvchi", "esp": "Piloto"},
  {"uz": "O’rtakash (Makler)", "esp": "Intermediario"},
  {"uz": "Matematik", "esp": "Matemático"},
  {"uz": "Menejer/Boshqaruvchi", "esp": "Gerente"},
  {"uz": "Mexanik", "esp": "Mecánico"},
  {"uz": "Mikrobiolog", "esp": "Microbiólogo"},
  {"uz": "Modeler", "esp": "diseñador de la ropa"},
  {"uz": "Dengizchi", "esp": "Marinero"},
  {"uz": "Musiqachi", "esp": "Músico"},
  {"uz": "Narkolog", "esp": "Narcólogo"},
  {"uz": "Izlanuvchi", "esp": "Investigador"},
  {"uz": "Operator", "esp": "Operador"},
  {"uz": "Pedagog", "esp": "Pedagogo"},
  {"uz": "Tarjimon", "esp": "Intérprete"},
  {"uz": "Firma vakili", "esp": "representante de la empresa"},
  {"uz": "Pedagog/O‘qituvchi", "esp": "Pedagogo"},
  {"uz": "Dasturchi", "esp": "Programador"},
  {"uz": "Prokuror", "esp": "Procurador"},
  {"uz": "Psixiatr", "esp": "Psiquiatra"},
  {"uz": "Ruhshunos", "esp": "Psicólogo"},
  {"uz": "Psixoterapevt", "esp": "Psicoterapeuta"},
  {"uz": "Ishchi", "esp": "Obrero"},
  {"uz": "Muharrir", "esp": "Redactor"},
  {"uz": "Rejisyor", "esp": "director de cine"},
  {"uz": "Baliqchi", "esp": "Pescador"},
  {"uz": "Santexnik", "esp": "Plomero"},
  {"uz": "Xudojo‘y", "esp": "Sacerdote"},
  {"uz": "Xaykaltarosh", "esp": "Escultor"},
  {"uz": "Xizmatchi", "esp": "Empleado"},
  {"uz": "Marketing bo‘yicha mutaxassis", "esp": "Marketólogo"},
  {"uz": "Sportchi", "esp": "Deportista"},
  {"uz": "Sudya, qozi", "esp": "Juez"},
  {"uz": "Terapevt", "esp": "Terapeuta"},
  {"uz": "O‘quvchi*", "esp": "alumno/a"},
  {"uz": "Olim", "esp": "Cientifico"},
  {"uz": "O‘qituvchi*", "esp": "Maestro/a"},
  {"uz": "Dorishunos", "esp": "Farmacéutico"},
  {"uz": "Fizik", "esp": "Físico"},
  {"uz": "Filolog, tilshunos", "esp": "Filólogo"},
  {"uz": "Faylasuf", "esp": "Filósofo"},
  {"uz": "Moliyachi", "esp": "Financista"},
  {"uz": "Suratchi", "esp": "Fotógrafo"},
  {"uz": "kimyogar", "esp": "Químico"},
  {"uz": "Jarroh", "esp": "Cirujano"},
  {"uz": "Rassom", "esp": "Pintor"},
  {"uz": "Gid", "esp": "Guía"},
  {"uz": "Maktab o‘quvchisi", "esp": "Escolar"},
  {"uz": "Iqtisodchi", "esp": "Economista"},
  {"uz": "Elektrik", "esp": "Electricista"},
  {"uz": "Huquqshunos", "esp": "Jurista"}
];
