List kema = [
  {
    "uz": "...ga kema nechchida ketadi?",
    "esp": "¿a qué hora sale el barco a... ?"
  },
  {
    "uz": "kemaga chiptani qayerdan olsa bo‘ladi?",
    "esp": "¿dónde se puede comprar billetes para el barco ?"
  },
  {
    "uz": "...ga chipta qancha turadi?",
    "esp": "¿cuánto cuesta el billete para... ?"
  },
  {
    "uz": "iltimos, menga....klassga ikkita chipta bering",
    "esp": "por favor, deme dos billetes de ...clase"
  },
  {"uz": "-birinchi", "esp": "-primera"},
  {"uz": "-ikkinchi", "esp": "-segunda"},
  {"uz": "-uchinchi", "esp": "-tercera"},
  {"uz": "Sayohat qancha davom etadi?", "esp": "¿Cuánto dura el viaje?"},
  {
    "uz": "Kema qaysi ....dan jo‘naydi?",
    "esp": "¿De qué atracadero sale el barco ?"
  },
  {"uz": "Qayerda to‘xtab o‘tadi?", "esp": "¿Dónd se hace escala?"},
  {
    "uz": "...da qancha vaqt to‘xtab turadi?",
    "esp": "¿Cuánto tiempo dura la escala en... ?"
  },
  {"uz": "...ga qachon etamiz?", "esp": "¿Cuándo llegamos a ...?"},
  {"uz": "Kemaga chiqish soat nechchida?", "esp": "¿A qué hora el embarco?"},
  {"uz": "Kayuta qayerda joylashgan?", "esp": "¿Dónde está el camarote...?"},
  {"uz": "... qanday boriladi", "esp": "¿Cómo se va...?"},
  {"uz": "-aylanish yo‘lagiga", "esp": "-a la cubierta de paseo"},
  {"uz": "-kafeteriyaga", "esp": "-a la cafeteria"},
  {"uz": "-barga", "esp": "-al bar"},
  {"uz": "-restoran", "esp": "-al restaurante"},
  {"uz": "o‘zimni yomon his qilayapman", "esp": "no me siento bien"},
  {"uz": "boshim aylanayapti", "esp": "estoy mareado (mareada)"},
  {"uz": "iltimos, doktorni chaqiring", "esp": "llame al medico, por favor"},
  {"uz": "zarur so‘zlar", "esp": "palabras utiles"},
  {"uz": "qirg‘oq", "esp": "costa"},
  {"uz": "shabada", "esp": "brisa"},
  {"uz": "buxta", "esp": "bahía"},
  {"uz": "shamol", "esp": "viento"},
  {"uz": "to‘lqin", "esp": "ola"},
  {"uz": "kemadan tushish", "esp": "desembarque"},
  {"uz": "dengizga chiqish", "esp": "hacerse a la mar"},
  {"uz": "bandargoh", "esp": "puerto"},
  {"uz": "golf", "esp": "golfo"},
  {
    "uz":
        "1.illyuminator 2. raketa, samolyot, kemalarda maxkam yopiladigan darcha",
    "esp": "portilla"
  },
  {"uz": "1. kanat 2. yo‘g‘on arqon", "esp": "amarra"},
  {"uz": "1.kapitan 2.sardor", "esp": "capitán"},
  {"uz": "kapitan ko‘prikchasi", "esp": "puente de mando"},
  {"uz": "chayqalish", "esp": "balanceo"},
  {"uz": "kayuta", "esp": "camarote"},
  {"uz": "oshpaz", "esp": "cocinero"},
  {"uz": "1.komanda 2.og‘zaki buyruq", "esp": "tripulación"},
  {"uz": "kema", "esp": "barco"},
  {"uz": "kema quyrug‘i", "esp": "popa"},
  {"uz": "dunyo bo‘ylab sayohat", "esp": "vuelta al mundo"},
  {"uz": "1.kruiz 2.dengiz sayohati", "esp": "crucero"},
  {"uz": "chekuvchilar joyi", "esp": "zona de fumadores"},
  {"uz": "qayiq", "esp": "lancha"},
  {"uz": "dengizchi", "esp": "marino"},
  {"uz": "machta", "esp": "mástil"},
  {"uz": "mayoq", "esp": "faro"},
  {"uz": "sayozlik, sayoz joy", "esp": "banco de arena"},
  {"uz": "dengiz", "esp": "mar"},
  {"uz": "dengiz kasalligi", "esp": "mareo"},
  {"uz": "dengiz sayohati", "esp": "viaje marítimo"},
  {"uz": "dengizchi", "esp": "marinero"},
  {"uz": "kema burni", "esp": "proa"},
  {"uz": "ko‘l", "esp": "lago"},
  {"uz": "okean", "esp": "océano"},
  {"uz": "orol", "esp": "isla"},
  {"uz": "ochiq dengiz", "esp": "alta mar"},
  {"uz": "dengizga chiqmoq", "esp": "zarpar"},
  {"uz": "1.paluba. 2 paroxod saxni", "esp": "cubierta..."},
  {"uz": "-yuqorigi", "esp": "-superior"},
  {"uz": "-pastki", "esp": "-inferior"},
  {"uz": "-sayilga chiquvchi", "esp": "-de paseo"},
  {"uz": "1.parom.2 solsimon yassi kema", "esp": "ferry"},
  {"uz": "qumli qirg‘oq", "esp": "costa arenosa"},
  {"uz": "1. plyaj, 2. sohil", "esp": "playa"},
  {"uz": "1.port, 2.bandargoh", "esp": "puerto"},
  {"uz": "port shahar", "esp": "ciudad portuaria"},
  {"uz": "kemalar to‘xtaydigan joy, 2.bandargoh", "esp": "muelle"},
  {
    "uz": "kemani qirg‘oqqa bog‘lab qo‘yish paytini kutib turish",
    "esp": "atracadero"
  },
  {"uz": "kemalarni to‘xtash joyiga bog‘lab qo‘ymoq", "esp": "atracar"},
  {"uz": "daryo", "esp": "río"},
  {"uz": "kemani boshqarish joyi", "esp": "camareta alta"},
  {"uz": "qutqaruv qayig‘i", "esp": "lancha salvavidas"},
  {"uz": "qutqaruv nimchasi", "esp": "chaleco salvavidas"},
  {"uz": "qutqaruv aylanasi", "esp": "flotador"},
  {"uz": "qutqaruv belbog‘i", "esp": "cinturón salvavidas"},
  {"uz": "qayiq", "esp": "nave"},
  {"uz": "kema", "esp": "barco"},
  {
    "uz": "1.trap 2.samolyot, kemalardan tushish yo‘lakchasi",
    "esp": "...escalerilla"
  },
  {"uz": "-tushirmoq", "esp": "-poner la..."},
  {"uz": "-yig‘ishtirmoq", "esp": "retirar la...."},
  {"uz": "quvur", "esp": "chimenea"},
  {"uz": "1.tryum. 2. Kema mexanizmlari o‘rnatilgan joy", "esp": "Bodega"},
  {"uz": "Bayroq", "esp": "Bandera"},
  {"uz": "1.shlyupka 2.qutqaruv qayig‘i", "esp": "Bote"},
  {"uz": "1.shtil. 2.shamolsiz vaqt", "esp": "Calma"},
  {"uz": "Langar", "esp": "Ancla"},
  {"uz": "1.Yaxta 2. Kichikroq kema", "esp": "Yate"},
];
