List kerakli6 = [
  {"uz": "ustara", "esp": "máquina de afeitar"},
  {"uz": "dezodorant", "esp": "desodorante"},
  {"uz": "atir", "esp": "perfume"},
  {"uz": "to‘g‘nog‘ich", "esp": "horquilla"},
  {"uz": "zontik", "esp": "paraguas"},
  {"uz": "tish yuvish pastasi", "esp": "pasta dentifica"},
  {"uz": "tish tozalash chyotkasi", "esp": "cepillo de dientes"},
  {"uz": "ninalar", "esp": "agujas"},
  {"uz": "krem-pudra", "esp": "crema de maquillaje"},
  {"uz": "ustara", "esp": "hoja de afeitar"},
  {"uz": "molniya zastejka", "esp": "cremallera"},
  {"uz": "sovun", "esp": "jabón"},
  {"uz": "yostiq jildi", "esp": "funda"},
  {"uz": "ip", "esp": "hilo"},
  {"uz": "odekolon", "esp": "agua de colonia"},
  {"uz": "odeyal", "esp": "manta"},
  {"uz": "ko‘z oynak", "esp": "gafas"},
  {"uz": "qo‘lqoplar", "esp": "guantes"},
  {"uz": "ko‘rpa", "esp": "manta"},
  {"uz": "ko‘rpa jildi", "esp": "funda de manta"},
  {"uz": "yostiq", "esp": "almohada"},
  {"uz": "pokrivalo", "esp": "colcha"},
  {"uz": "choyshab", "esp": "sábana"},
  {"uz": "to’qish ipi", "esp": "hilado"},
  {"uz": "upa", "esp": "polvos..."},
  {"uz": "-suyuq", "esp": "-liquidos"},
  {"uz": "-kompakt", "esp": "-compactos"},
  {"uz": "taroq", "esp": "peine"},
  {"uz": "belbog‘", "esp": "cinturón"},
  {"uz": "soat uchun tasma", "esp": "correa de reloj"},
  {"uz": "sumka", "esp": "bolso"},
  {"uz": "chemodan", "esp": "maleta"},
  {"uz": "shampun", "esp": "champu"},
  {"uz": "soch to‘g‘nog‘ich", "esp": "horquillas"},
  {"uz": "cho‘tka", "esp": "cepillo"},
];
