List kerakli7 = [
  {"uz": "engsiz jemper", "esp": "chaleco"},
  {"uz": "ich kiyim", "esp": "ropa"},
  {"uz": "bluza", "esp": "blusa"},
  {"uz": "shim", "esp": "pantalones"},
  {"uz": "byustgalter", "esp": "sostén"},
  {"uz": "yoqali jemper", "esp": "jersey de cuello alto"},
  {"uz": "Bo‘yinbog‘", "esp": "corbata"},
  {"uz": "golfi", "esp": "míni medias"},
  {"uz": "jemper", "esp": "jersey"},
  {"uz": "jinsi", "esp": "vaqueros"},
  {"uz": "dublyonka", "esp": "pellica"},
  {"uz": "jilet", "esp": "chaleco"},
  {"uz": "shapka", "esp": "visrea"},
  {"uz": "kolgotki", "esp": "pantys"},
  {"uz": "kostyum", "esp": "traje"},
  {"uz": "cho‘milish kiyimi", "esp": "bañador"},
  {"uz": "kurtka", "esp": "cazadora"},
  {"uz": "ich kiyim", "esp": "camesita"},
  {"uz": "paypoq", "esp": "calcetines"},
  {"uz": "palto", "esp": "abrigo"},
  {"uz": "pidjak", "esp": "chaqueta"},
  {"uz": "cho‘milish kiyimi", "esp": "bañador"},
  {"uz": "ko‘ylak", "esp": "vestido"},
  {"uz": "yomg‘irpo‘sh", "esp": "impremeable"},
  {"uz": "belbog‘", "esp": "cinturón"},
  {"uz": "pulover", "esp": "pulóver"},
  {"uz": "ayollar ko‘ylagi", "esp": "camisa"},
  {"uz": "erkaklar ko‘ylagi", "esp": "camisa"},
  {"uz": "sport kostyumi", "esp": "traje deportivo"},
  {"uz": "ich kiyim", "esp": "bragas (ayollar), calzoncillos (erkaklar)"},
  {"uz": "xalat", "esp": "bata"},
  {"uz": "chulki", "esp": "medias"},
  {"uz": "sharf", "esp": "bufandas"},
  {"uz": "shlyapa", "esp": "sombrero"},
  {"uz": "mo‘ynali kiyim", "esp": "pelliza"},
  {"uz": "yubka", "esp": "falda"},
  {"uz": "materiallar", "esp": "telas"},
  {"uz": "duxoba, baxmal", "esp": "terciopelo"},
  {"uz": "velvet", "esp": "pana"},
  {"uz": "velyur", "esp": "felpa"},
  {"uz": "viskoza", "esp": "viscosa"},
  {"uz": "djersi", "esp": "jersey"},
  {
    "uz": "bug‘u. qo‘y va boshqa hayvonlar terisidan tikilgan charm nimcha",
    "esp": "gamuza"
  },
  {"uz": "tabiiy charm", "esp": "cuero natural"},
  {"uz": "sun’iy charm", "esp": "piel artificial"},
  {"uz": "charm", "esp": "cuero"},
  {"uz": "lyon", "esp": "lino"},
  {"uz": "mo‘yna", "esp": "piel"},
  {"uz": "trikotaj", "esp": "género de punto"},
  {"uz": "paxta", "esp": "algodón"},
  {"uz": "ipak", "esp": "seda"},
  {"uz": "jun", "esp": "lana"},
];
