List kerakli2 = [
  {"uz": "1. astra. 2. qo‘qon gul", "esp": "aster"},
  {"uz": "guldasta", "esp": "ramo"},
  {"uz": "1.gvozdika. 2.chinnigul", "esp": "clavel"},
  {"uz": "gerbera", "esp": "gerbera"},
  {"uz": "1.giatsint 2.sunbul", "esp": "jacinto"},
  {"uz": "gipsofila", "esp": "hipsofila"},
  {"uz": "bezatish lenta", "esp": "cinta decorativa"},
  {"uz": "1.iris.2. gulsapsar", "esp": "iris"},
  {"uz": "kalla", "esp": "cala"},
  {"uz": "liliya", "esp": "azucena"},
  {"uz": "narsiss", "esp": "narcíso"},
  {"uz": "paparotnik", "esp": "helecho"},
  {"uz": "pion", "esp": "peonía"},
  {"uz": "roza", "esp": "rosa"},
  {"uz": "1.romashka2. moychechak", "esp": "manzanilla"},
  {"uz": "lola", "esp": "tulipán"},
  {"uz": "floks", "esp": "flox"},
  {"uz": "freziya", "esp": "fresia"},
];
