List kerakli8 = [
  {"uz": "yuk aravasi", "esp": "carretilla"},
  {"uz": "yuk vagoni", "esp": "furgón de equipajes"},
  {"uz": "vagon", "esp": "coche"},
  {"uz": "vagon restoran", "esp": "coche comedor"},
  {"uz": "bekat", "esp": "estación"},
  {"uz": "temir yo‘l", "esp": "ferrocarril"},
  {"uz": "mashinist", "esp": "conductor"},
  {"uz": "chipta tekshiruvchi", "esp": "revisor"},
  {"uz": "Kupe", "esp": "departamento"},
  {"uz": "...joy", "esp": "asiento..."},
  {"uz": "-yuqoridagi", "esp": "-la arriba"},
  {"uz": "-pastdagi", "esp": "-de abajo"},
  {"uz": "bekat boshlig‘i", "esp": "jefe de la estación"},
  {"uz": "to‘xtash", "esp": "parada"},
  {"uz": "perron", "esp": "andén"},
  {"uz": "...poezd", "esp": "tren..."},
  {"uz": "shaharlararo", "esp": "-de largos recorridos"},
  {"uz": "avtobus", "esp": "-omnibús"},
  {"uz": "shahar atrofi", "esp": "-de cercanías"},
  {"uz": "-tezyurar", "esp": "-rápido"},
  {"uz": "...joy", "esp": "litera..."},
  {"uz": "-yuqoridagi", "esp": "-de arriba"},
  {"uz": "-pastdagi", "esp": "-de abajo"},
  {"uz": "vagon kuzatuvchisi", "esp": "jefe/mozo del vagón"},
  {"uz": "bekat", "esp": "estación"},
  {"uz": "favqulodda to‘xtash", "esp": "freno de emergencia"},
  {"uz": "bekat", "esp": "parada"},
  {"uz": "tezyurar", "esp": "expreso"},
  {"uz": "shaharlararo poezd", "esp": "tren de cercanías"},
];
