List kerakli = [
  {"uz": "kichkina likopcha", "esp": "platillo"},
  {"uz": "bilaguzuk", "esp": "pulsera"},
  {"uz": "sanchqi", "esp": "tenedor"},
  {"uz": "archa o‘yinchoqlari", "esp": "juguetes de árbol de navidad"},
  {"uz": "ilma tugma", "esp": "gemelos"},
  {"uz": "tilla", "esp": "oro"},
  {"uz": "sun’iy archa", "esp": "abeto artificial"},
  {"uz": "shoda, marjon", "esp": "collar"},
  {"uz": "uzuk", "esp": "anillo"},
  {"uz": "krujka", "esp": "jarro"},
  {"uz": "marjon", "esp": "colgante"},
  {"uz": "qoshiq", "esp": "cuchara"},
  {"uz": "pichoq", "esp": "cuchillo"},
  {"uz": "qayroq", "esp": "afiladora de cuchillos"},
  {"uz": "kumush", "esp": "plata"},
  {"uz": "xalqa", "esp": "pendientes"},
  {"uz": "spinning", "esp": "spinning"},
  {"uz": "likopcha", "esp": "plato"},
  {"uz": "qarmoq", "esp": "caña de pescar"},
  {"uz": "zanjir", "esp": "cadenita"},
  {"uz": "1. chashka 2. dastali piyola", "esp": "taza"},
  {"uz": "quti", "esp": "estuche"},
  {"uz": "ochqich", "esp": "sacacorchos"},
];
