List kerakli5 = [
  {"uz": "audiokasseta", "esp": "audiocassete"},
  {"uz": "batareya", "esp": "pila"},
  {"uz": "qo’ng’iroq", "esp": "despertador"},
  {"uz": "videokamera", "esp": "cámara de video"},
  {"uz": "videokasseta", "esp": "videocassete"},
  {"uz": "video", "esp": "vídeo"},
  {"uz": "kalkulyator", "esp": "calculadora"},
  {"uz": "kasseta", "esp": "casete"},
  {"uz": "kompyuter klaviaturasi", "esp": "teclado"},
  {"uz": "kompakt disk", "esp": "CD-disco"},
  {"uz": "kompyuter", "esp": "ordenador"},
  {"uz": "kofe tayyorlagich", "esp": "cafetera"},
  {"uz": "oshxona kombayni", "esp": "batidora picadora"},
  {"uz": "qandil", "esp": "araña"},
  {"uz": "magnitofon", "esp": "grabadora"},
  {"uz": "mikroto‘lqinli pech", "esp": "microondas"},
  {"uz": "1.mikser 2. aralashtirgich", "esp": "batidora"},
  {"uz": "modem", "esp": "modem"},
  {"uz": "1.monitor 2.ekran", "esp": "monitor"},
  {"uz": "quloqda eshitgich", "esp": "auriculares"},
  {"uz": "noutbuk", "esp": "ordenador portátil"},
  {"uz": "pleer", "esp": "player"},
  {"uz": "printer", "esp": "impresora"},
  {"uz": "chang yutgich", "esp": "aspiradora"},
  {"uz": "radio soat", "esp": "radio-reloj-despertador"},
  {"uz": "yoritgich", "esp": "candil"},
  {"uz": "televizor", "esp": "televisor"},
  {"uz": "toster", "esp": "tostador"},
  {"uz": "dazmol", "esp": "plancha"},
  {"uz": "1.fen 2.soch quritgich", "esp": "secador de pelo"},
  {"uz": "fotoapparat", "esp": "cámara de fotos"},
  {"uz": "fotoplyonka", "esp": "carrete de fotos"},
  {"uz": "...soat", "esp": "reloj..."},
  {"uz": "-qo‘l", "esp": "-de pulsera"},
  {"uz": "-osma", "esp": "-de pared"},
  {"uz": "tikuv mashinasi", "esp": "máquina de coser"},
  {"uz": "elektr choynak", "esp": "tetera eléctrica"},
  {"uz": "elektr soqol olgich", "esp": "máquina de afeitar"},
];
