List obHavo = [
  {"uz": "Sizda iqlim qanaqa?", "esp": "¿Qué clima tienen?"},
  {"uz": "Bizda iqlim ...", "esp": "Tenemos un clima ..."},
  {"uz": "-o‘zgaruvchan", "esp": "-continental"},
  {"uz": "-keskin o‘zgaruvchan", "esp": "-extremo"},
  {"uz": "-dengiz", "esp": "-marítimo"},
  {"uz": "-subtropik", "esp": "-subtropical"},
  {"uz": "-o‘rta yer dengizidagidek", "esp": "-mediterráneo"},
  {"uz": "-tropik", "esp": "-tropical"},
  {
    "uz": "Sizlarda namlik yuqorimi (pastmi)?",
    "esp": "¿Tienen alta (baja) humedad?"
  },
  {
    "uz": "Sizlarda qish qattiq (yumshoq) bo‘ladimi?",
    "esp": "Y el invierno, ¿es riguroso (suave)?"
  },
  {"uz": "Sizlarda yoz issiq bo‘ladimi?", "esp": "Y el verano, ¿es caluroso?"},
  {
    "uz": "Sizlarda..... o‘rtacha harorat qanaqa bo‘ladi?",
    "esp": "¿Cuál es la temperatura media...?"
  },
  {"uz": "-qishda", "esp": "-en invierno"},
  {"uz": "-bahorda", "esp": "-en primavera"},
  {"uz": "-yozda", "esp": "-en verano"},
  {"uz": "-kuzda", "esp": "-en otoño"},
  {"uz": ".....dan yuqori", "esp": "...grados sobre cero"},
  {"uz": "Qishda qor yog‘adimi?", "esp": "¿Nieva en invierno?"},
  {"uz": "Bugun ob-havo qanaqa?", "esp": "¿Qué tiempo hace hoy?"},
  {"uz": "Bugun tashqarida...", "esp": "Hoy...."},
  {"uz": "-issiq", "esp": "-hace calor"},
  {"uz": "-sovuq", "esp": "-hace frio"},
  {"uz": "-yomg‘ir yog‘adi", "esp": "-llueve"},
  {"uz": "-dim", "esp": "-hace bochorno"},
  {"uz": "-bulutli", "esp": "-está nublado"},
  {"uz": "-salqin", "esp": "-hace fresco"},
  {"uz": "-shamol", "esp": "-hace viento"},
  {"uz": "-ochiq", "esp": "-esta despejado"},
  {"uz": "-quyoshli", "esp": "-hace sol"},
  {"uz": "-sovuq", "esp": "-hace frio"},
  {"uz": "-bo‘ron", "esp": "-hace ventisca"},
  {"uz": "Osmon ...", "esp": "El cielo está....."},
  {"uz": "-ko‘m-ko‘k", "esp": "-azul"},
  {"uz": "-bulutsiz", "esp": "-sin nubes"},
  {"uz": "-ochiq", "esp": "-despejado"},
  {"uz": "-bulutli", "esp": "-nublado"},
  {"uz": "Yomg‘ir yog‘ayapti", "esp": "Llueve"},
  {"uz": "Qor yog‘yapti", "esp": "Nieva"},
  {"uz": "Do‘l yog‘yapti", "esp": "Graniza"},
  {"uz": "Kuchli shamol esyapti", "esp": "Hace mucho viento"},
  {"uz": "Kuchli yomg‘ir yog‘yapti", "esp": "Esta diluviando"},
  {"uz": "Sovib qoldi", "esp": "Hace más frío ..."},
  {"uz": "Kecha kun bo‘yi ...", "esp": "Ayer todo el día ..."},
  {"uz": "-issiq bo‘ldi", "esp": "-hizo calor"},
  {"uz": "-sovuq bo‘ldi", "esp": "-hizo frío"},
  {"uz": "-yomg‘ir yog‘di", "esp": "-llovió"},
  {"uz": "Bugun ob-havo juda yaxshi", "esp": "Hoy hace muy buen tiempo"},
  {
    "uz": "Ertaga ob-havo qanday bo‘ladi?",
    "esp": "¿Cuál es el pronóstico del tiempo para mañana ?"
  },
  {"uz": "Ertaga ...", "esp": "Mañana …"},
  {"uz": "-iliq bo‘ladi", "esp": "-hará un dia templado"},
  {"uz": "-issiq bo‘ladi", "esp": "-hará calor"},
  {"uz": "-sovuq bo‘ladi", "esp": "-hará frio"},
  {"uz": "-yomg‘ir yog‘adi", "esp": "-lloverá"},
  {"uz": "-tuman bo‘ladi", "esp": "-habrá niebla"},
  {"uz": "-do‘l yog‘adi", "esp": "-habra tormenta"},
  {
    "uz": "Bugun suvning harorati qanday?",
    "esp": "¿Cuál es la temperatura del agua hoy ?"
  },
  {"uz": "Dengizda to‘lqinlar qanday?", "esp": "¿Cómo es la marejada?"},
  {"uz": "Necha ball?", "esp": "¿Cuántos grados hay?"},
  {"uz": "Dengizda dovul bor", "esp": "El mar está borrascoso"},
  {"uz": "Bugun dovul bo‘ldi.", "esp": "Hoy se ha desencadenado una borrasca"},
  {"uz": "Cho‘milish taqiqlanadi.", "esp": "Prohibido bañarse"}
];
