List sport = [
  {
    "uz": "Siz qaysi sport turiga qiziqasiz?",
    "esp": "¿A qué deporte es usted aficionado?"
  },
  {"uz": "Jon deb...borgan bo'lardm", "esp": "Con mucho gusto vería..."},
  {"uz": "-futbolga", "esp": "-un partido de futbol"},
  {
    "uz": "-muz ustidagi xokkeyga",
    "esp": "-un partido de hockey sobre el hielo"
  },
  {
    "uz": "-figurali uchish musobaqalariga",
    "esp": "-competeciones de patinaje artístico"
  },
  {"uz": "-tennis turniriga", "esp": "-un torneo de tenis"},
  {
    "uz": "Siz qaysi sport bilan shug'ullnasiz?",
    "esp": "¿Qué deportes practica usted? "
  },
  {"uz": "Men....bilan sug'ullanman", "esp": "Yo practico..."},
  {"uz": "-suzish ", "esp": "-la natación"},
  {"uz": "-qilichbozlk", "esp": "-el esgrima"},
  {"uz": "-kurash", "esp": "-la lucha"},
  {"uz": "Men...o'ynayma", "esp": "Yo juego al..."},
  {"uz": "-voleybol", "esp": "-balónmano"},
  {"uz": "-basketbol", "esp": "-balancesto"},
  {"uz": "-shaxmat", "esp": "-ajedrez"},
  {
    "uz": "Siz qaysi jamoaga muxlislik qilsiz?",
    "esp": "¿De qué equipo es usted hincha?"
  },
  {"uz": "Bugun kim o'ynayd?", "esp": "¿Quién juega hoy?"},
  {"uz": "O'yin qachon boshlanadi?", "esp": "¿Cuándo comienza el juego?"},
  {"uz": "...raqamda kim o'ynaydi?", "esp": "¿Quién es el número...? "},
  {"uz": "Hisob qanaqa?", "esp": "¿Cómo va el tanteo?"},
  {
    "uz": ".... jamoasi 2:1 hisobida yutdi",
    "esp": "El equipo... va ganado por dos o uno"
  },
  {
    "uz": "...jamoasi 2:3 hisobida yutqazdi ",
    "esp": "El equipo... perdio por dos a tres"
  },
  {"uz": "Jamoalar durang o'ynashd", "esp": "Los equipos han empatado"},
  {"uz": "Kim...o'rinni egalladi?", "esp": "¿Quén ha ocupado...lugar?"},
  {"uz": "-birinchi", "esp": "-el primer"},
  {"uz": "-ikkinchi", "esp": "-el segundo"},
  {"uz": "-uchunchi", "esp": "-el tercer"},
  {"uz": "Kim yutdi?", "esp": "¿Quién ha ganado?"},
  {"uz": "Mening sevimli sport turim...", "esp": "Mi deporte preferido es..."},
  {"uz": "-ot sporti", "esp": "-equitación"},
  {"uz": "-paruli sport", "esp": "-vela"},
  {"uz": "-tog' chang'i spoti", "esp": "-esquí de montaña"},
  {"uz": "-syorfin", "esp": "-surfing"},
  {"uz": "-golf", "esp": "-golf"},
  {"uz": "-fristayl", "esp": "-freestyle"},
  {"uz": "-bouling", "esp": "-bowling"},
  {"uz": "Roliklar", "esp": "-patines de ruedas"},
  {"uz": "Kerakli so'zlar", "esp": "Palabras utiles"},
  {"uz": "avtomobil poygalari", "esp": "carrera de automóviles"},
  {"uz": "alpinizm", "esp": "alpinismo"},
  {"uz": "kanoe", "esp": "canoa"},
  {"uz": "basketbol", "esp": "baloncesto"},
  {"uz": "...yugiris", "esp": "carrera..."},
  {"uz": "-uzoq masfalarga", "esp": "-de fondo"},
  {"uz": "-qisqa masofaarga", "esp": "-de velocidad"},
  {"uz": "-to'siqlar osha", "esp": "-con obstáculos"},
  {"uz": "biatlon", "esp": "biatlón"},
  {"uz": "boks", "esp": "boxeo"},
  {"uz": "muxlis", "esp": "hincha"},
  {"uz": "...kuras", "esp": "lucha..."},
  {"uz": "-erkin", "esp": "-libre"},
  {"uz": "-grek rim", "esp": "-grecorromana"},
  {"uz": "bouling", "esp": "bowling"},
  {"uz": "velospor", "esp": "ciclismo"},
  {"uz": "syorfin", "esp": "surfing"},
  {"uz": "suv polosi", "esp": "polo acuático"},
  {"uz": "voleybol", "esp": "vóleibol"},
  {"uz": "....gimnstika", "esp": "gimnasia"},
  {"uz": "-sport", "esp": "-deportiva"},
  {"uz": "-ritmik", "esp": "-rítmica"},
  {"uz": "gimnastia zali", "esp": "gimnasio"},
  {"uz": "gol", "esp": "gol"},
  {"uz": "golf", "esp": "golf"},
  {"uz": "eshkk eshish", "esp": "remo"},
  {"uz": "darts", "esp": "darts"},
  {"uz": "dzyuo", "esp": "judo"},
  {"uz": "tomoshabin", "esp": "espectador"},
  {"uz": "o'yin", "esp": "juego"},
  {"uz": "o'yinch", "esp": "jugador"},
  {"uz": "kanoe", "esp": "canoa"},
  {"uz": "jamoa sardori", "esp": "capítan del equipo"},
  {"uz": "karate", "esp": "kárate"},
  {"uz": "jamoa", "esp": "equipo"},
  {"uz": "ot spoti", "esp": "hípica"},
  {"uz": "konki", "esp": "patines"},
  {"uz": "konkida ugurish porti", "esp": "patinaje"},
  {"uz": "kubo", "esp": "copa"},
  {"uz": "atletizm", "esp": "atletismo"},
  {"uz": "changi", "esp": "esquí"},
  {"uz": "changi sporti", "esp": "esquí"},
  {"uz": "match", "esp": "partido"},
  {"uz": "...medal", "esp": "medalla..."},
  {"uz": "-oltin", "esp": "-de oro"},
  {"uz": "-kumush", "esp": "-de plata"},
  {"uz": "-bronza", "esp": "-de bronce"},
  {"uz": "...o'rin", "esp": "...lugar"},
  {"uz": "-birinchi", "esp": "-el primer"},
  {"uz": "-ikkinchi", "esp": "-el segundo"},
  {"uz": "-uchinchi", "esp": "-el tercer"},
  {"uz": "...uloqtirish", "esp": "Lanzamiento..."},
  {"uz": "-disk", "esp": "-de disco"},
  {"uz": "-nayza", "esp": "-de la jabalina"},
  {"uz": "-bolg'a", "esp": "-del martillo"},
  {"uz": "ko'p kursh", "esp": "politlón"},
  {"uz": "durang", "esp": "empate"},
  {"uz": "olimpiada", "esp": "olimpiada"},
  {"uz": "olimpiya qishlg'i", "esp": "villa olímpica"},
  {"uz": "olimpiya o'yinlai", "esp": "juegos olímpicos"},
  {"uz": "olimpiya chempioi", "esp": "campeón olímpico"},
  {"uz": "saralash musobaqalari", "esp": "pruebas eliminatorias"},
  {"uz": "elkanli sporti", "esp": "deporte de vela"},
  {"uz": "..suzish", "esp": "natación..."},
  {"uz": "-suv ostid", "esp": "-submarina"},
  {"uz": "-sinxron", "esp": "-sincrónica"},
  {"uz": "suv xafasi", "esp": "piscina"},
  {"uz": "yarim final", "esp": "la semifinal"},
  {"uz": "o'yin qoidalari", "esp": "reglas del juego"},
  {"uz": "mukofo", "esp": "premio"},
  {"uz": "g'olib", "esp": "vencedor"},
  {"uz": "..sakrash", "esp": "saltos..."},
  {"uz": "-balandlika", "esp": "-de altura"},
  {"uz": "-uzunlikka", "esp": "-de longitud"},
  {"uz": "-langar bila ", "esp": "-con pértiga"},
  {"uz": "echinish xoasi", "esp": "guardarropa"},
  {"uz": "regata", "esp": "regata"},
  {"uz": "natija", "esp": "resultado"},
  {"uz": "rekord", "esp": "récord"},
  {"uz": "rekordchi", "esp": "recordista"},
  {"uz": "sambo", "esp": "sambo"},
  {"uz": "musobaqa", "esp": "competición"},
  {"uz": "sport", "esp": "deporte"},
  {"uz": "sport klubi", "esp": "club deportivo"},
  {"uz": "sportchi", "esp": "deportista"},
  {"uz": "stadion", "esp": "estadio"},
  {"uz": "o'q tish klui", "esp": "tiro"},
  {"uz": "xakam", "esp": "árbitro"},
  {"uz": "hisob", "esp": "tanteo, punteo"},
  {"uz": "vaqt", "esp": "tiempo"},
  {"uz": "tenni", "esp": "tenís"},
  {"uz": "trener", "esp": "entrenador"},
  {"uz": "shug'ullanish", "esp": "entrenamiento"},
  {"uz": "tribuna", "esp": "tribuna"},
  {"uz": "og'ir atletia", "esp": "halterofilia"},
  {"uz": "qilichbzlik", "esp": "esgrima"},
  {"uz": "figurali uchish", "esp": "patenaje artistico"},
  {"uz": "futbol", "esp": "fútbol"},
  {"uz": "xokkey", "esp": "hockey"},
  {"uz": "chempio", "esp": "campeón"},
  {"uz": "chempionat", "esp": "campeonato"},
  {"uz": "chorak final", "esp": "cuarto de final"},
  {"uz": "shaxmat", "esp": "ajedrez"},
  {"uz": "shtanga", "esp": "barra de discos, pesa"},
  {"uz": "yaxt", "esp": "yate"},
];
