List tilakVaIstaklar = [
  {"uz": "Sizni....bilan tabriklayman", "esp": "Le felecito con motivo..."},
  {"uz": "-tug‘ilgan kuningiz", "esp": "-de su cumpleaños"},
  {"uz": "-bayram", "esp": "-de la fiesta"},
  {"uz": "-yangi yil", "esp": "-por Año Nuevo"},
  {"uz": "-yubiley", "esp": "-del aniversario"},
  {"uz": "Sizga.... tilayman", "esp": "Le deseo...."},
  {"uz": "-baxt", "esp": "-felicidad"},
  {"uz": "-muvaffaqiyatlar", "esp": "-éxitos"},
  {"uz": "-mustahkam sog‘liq", "esp": "-buena salud"},
  {"uz": "-omad", "esp": "-suerte"},
  {"uz": "-uzoq umr", "esp": "-muchos años de vida"},
  {"uz": "-oq yo‘l", "esp": "-buen viaje"},
  {"uz": "-qiziqarli sayohat", "esp": "-un viaje interesante"},
  {"uz": "-yaxshi dam", "esp": "-buen descanso"},
  {"uz": "Omad sizga!", "esp": "¡Suerte!"},
  {"uz": "Sog‘ bo‘ling!", "esp": "¡Salud!"},
  {"uz": "Mustahkam sog‘liq tilayman!", "esp": "¡Qué tenga mucha salud!"},
  {"uz": "O‘zingizni ehtiyot qiling!", "esp": "¡Cuídese!"}
];
