List zargarlikKerakliSozlar = [
  {"uz": "aqiq", "esp": "ágata"},
  {"uz": "safsar", "esp": "amatista"},
  {"uz": "feruza", "esp": "turquesa"},
  {"uz": "bilaguzuk", "esp": "pulsera"},
  {"uz": "brilliant", "esp": "brillante"},
  {"uz": "to‘g‘nag‘ich", "esp": "broche"},
  {"uz": "qimmatbaho tosh", "esp": "piedra preciosa"},
  {"uz": "marvarid, dur, inju", "esp": "perla"},
  {"uz": "ilma tugma", "esp": "gemelos"},
  {"uz": "tilla", "esp": "oro"},
  {"uz": "zumrad", "esp": "esmeralda"},
  {"uz": "shoda, marjon", "esp": "collar"},
  {"uz": "uzuk", "esp": "anillo"},
  {"uz": "marjon, zanjir", "esp": "colgante"},
  {"uz": "marjon, shoda", "esp": "collar"},
  {"uz": "erkaklar uzugi", "esp": "sortija"},
  {"uz": "muhrli uzuk", "esp": "sello"},
  {"uz": "platina, oq oltin", "esp": "platino"},
  {"uz": "tilla suvi yuritilgan", "esp": "chapado en oro"},
  {"uz": "sigaret qutisi", "esp": "pitillera"},
  {"uz": "kumush suvi yuritilgan", "esp": "chapado en plata"},
  {"uz": "soat uchun remeshok", "esp": "correa de reloj"},
  {"uz": "la’l", "esp": "rubí"},
  {"uz": "yoqut", "esp": "zafiro"},
  {"uz": "kumush", "esp": "plata"},
  {"uz": "xalqa", "esp": "pendientes"},
  {"uz": "fil suyagi", "esp": "marfil"},
  {
    "uz": "kumush suvi yugurtirilgan oshxona anjomlari",
    "esp": "cubertería de plata"
  },
  {"uz": "qimmatbaho yaltiroq tosh", "esp": "topacio"},
  {"uz": "zanjir", "esp": "cadenita"},
  {"uz": "...soat", "esp": "reloj..."},
  {"uz": "- qo‘l", "esp": "-de pulsera"},
  {"uz": "- osma", "esp": "-de pared"},
  {"uz": "qimmatbaho mahsulotlar", "esp": "joyería"},
  {"uz": "yoqut", "esp": "ámbar"},
];
